// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.17.3
// source: api/user/pb/user.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type LigthPayReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Account int32  `protobuf:"varint,1,opt,name=account,proto3" json:"account,omitempty"`
	LogDesc string `protobuf:"bytes,2,opt,name=logDesc,proto3" json:"logDesc,omitempty"`
	OpenId  string `protobuf:"bytes,3,opt,name=openId,proto3" json:"openId,omitempty"`
	UserId  int32  `protobuf:"varint,4,opt,name=userId,proto3" json:"userId,omitempty"`
}

func (x *LigthPayReq) Reset() {
	*x = LigthPayReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_user_pb_user_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LigthPayReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LigthPayReq) ProtoMessage() {}

func (x *LigthPayReq) ProtoReflect() protoreflect.Message {
	mi := &file_api_user_pb_user_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LigthPayReq.ProtoReflect.Descriptor instead.
func (*LigthPayReq) Descriptor() ([]byte, []int) {
	return file_api_user_pb_user_proto_rawDescGZIP(), []int{0}
}

func (x *LigthPayReq) GetAccount() int32 {
	if x != nil {
		return x.Account
	}
	return 0
}

func (x *LigthPayReq) GetLogDesc() string {
	if x != nil {
		return x.LogDesc
	}
	return ""
}

func (x *LigthPayReq) GetOpenId() string {
	if x != nil {
		return x.OpenId
	}
	return ""
}

func (x *LigthPayReq) GetUserId() int32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type LigthPayResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *LigthPayResp) Reset() {
	*x = LigthPayResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_user_pb_user_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LigthPayResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LigthPayResp) ProtoMessage() {}

func (x *LigthPayResp) ProtoReflect() protoreflect.Message {
	mi := &file_api_user_pb_user_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LigthPayResp.ProtoReflect.Descriptor instead.
func (*LigthPayResp) Descriptor() ([]byte, []int) {
	return file_api_user_pb_user_proto_rawDescGZIP(), []int{1}
}

type CreateVerifyCodeReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PhoneNum string `protobuf:"bytes,1,opt,name=PhoneNum,proto3" json:"PhoneNum,omitempty"` //手机号
}

func (x *CreateVerifyCodeReq) Reset() {
	*x = CreateVerifyCodeReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_user_pb_user_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateVerifyCodeReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateVerifyCodeReq) ProtoMessage() {}

func (x *CreateVerifyCodeReq) ProtoReflect() protoreflect.Message {
	mi := &file_api_user_pb_user_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateVerifyCodeReq.ProtoReflect.Descriptor instead.
func (*CreateVerifyCodeReq) Descriptor() ([]byte, []int) {
	return file_api_user_pb_user_proto_rawDescGZIP(), []int{2}
}

func (x *CreateVerifyCodeReq) GetPhoneNum() string {
	if x != nil {
		return x.PhoneNum
	}
	return ""
}

type CreateVerifyCodeRsp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *CreateVerifyCodeRsp) Reset() {
	*x = CreateVerifyCodeRsp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_user_pb_user_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateVerifyCodeRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateVerifyCodeRsp) ProtoMessage() {}

func (x *CreateVerifyCodeRsp) ProtoReflect() protoreflect.Message {
	mi := &file_api_user_pb_user_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateVerifyCodeRsp.ProtoReflect.Descriptor instead.
func (*CreateVerifyCodeRsp) Descriptor() ([]byte, []int) {
	return file_api_user_pb_user_proto_rawDescGZIP(), []int{3}
}

type LoginByPhoneReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PhoneNum   string `protobuf:"bytes,1,opt,name=PhoneNum,proto3" json:"PhoneNum,omitempty"` //手机号
	UserName   string `protobuf:"bytes,2,opt,name=UserName,proto3" json:"UserName,omitempty"`
	VerifyCode string `protobuf:"bytes,3,opt,name=VerifyCode,proto3" json:"VerifyCode,omitempty"`
}

func (x *LoginByPhoneReq) Reset() {
	*x = LoginByPhoneReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_user_pb_user_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LoginByPhoneReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginByPhoneReq) ProtoMessage() {}

func (x *LoginByPhoneReq) ProtoReflect() protoreflect.Message {
	mi := &file_api_user_pb_user_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginByPhoneReq.ProtoReflect.Descriptor instead.
func (*LoginByPhoneReq) Descriptor() ([]byte, []int) {
	return file_api_user_pb_user_proto_rawDescGZIP(), []int{4}
}

func (x *LoginByPhoneReq) GetPhoneNum() string {
	if x != nil {
		return x.PhoneNum
	}
	return ""
}

func (x *LoginByPhoneReq) GetUserName() string {
	if x != nil {
		return x.UserName
	}
	return ""
}

func (x *LoginByPhoneReq) GetVerifyCode() string {
	if x != nil {
		return x.VerifyCode
	}
	return ""
}

type TokenResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Token    string `protobuf:"bytes,1,opt,name=Token,proto3" json:"Token,omitempty"`
	PhoneNum string `protobuf:"bytes,2,opt,name=PhoneNum,proto3" json:"PhoneNum,omitempty"` //手机号
	UserName string `protobuf:"bytes,3,opt,name=UserName,proto3" json:"UserName,omitempty"`
}

func (x *TokenResp) Reset() {
	*x = TokenResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_user_pb_user_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TokenResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TokenResp) ProtoMessage() {}

func (x *TokenResp) ProtoReflect() protoreflect.Message {
	mi := &file_api_user_pb_user_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TokenResp.ProtoReflect.Descriptor instead.
func (*TokenResp) Descriptor() ([]byte, []int) {
	return file_api_user_pb_user_proto_rawDescGZIP(), []int{5}
}

func (x *TokenResp) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *TokenResp) GetPhoneNum() string {
	if x != nil {
		return x.PhoneNum
	}
	return ""
}

func (x *TokenResp) GetUserName() string {
	if x != nil {
		return x.UserName
	}
	return ""
}

var File_api_user_pb_user_proto protoreflect.FileDescriptor

var file_api_user_pb_user_proto_rawDesc = []byte{
	0x0a, 0x16, 0x61, 0x70, 0x69, 0x2f, 0x75, 0x73, 0x65, 0x72, 0x2f, 0x70, 0x62, 0x2f, 0x75, 0x73,
	0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x04, 0x75, 0x73, 0x65, 0x72, 0x22, 0x71,
	0x0a, 0x0b, 0x4c, 0x69, 0x67, 0x74, 0x68, 0x50, 0x61, 0x79, 0x52, 0x65, 0x71, 0x12, 0x18, 0x0a,
	0x07, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x07,
	0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x6c, 0x6f, 0x67, 0x44, 0x65,
	0x73, 0x63, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6c, 0x6f, 0x67, 0x44, 0x65, 0x73,
	0x63, 0x12, 0x16, 0x0a, 0x06, 0x6f, 0x70, 0x65, 0x6e, 0x49, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x06, 0x6f, 0x70, 0x65, 0x6e, 0x49, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x75, 0x73, 0x65,
	0x72, 0x49, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49,
	0x64, 0x22, 0x0e, 0x0a, 0x0c, 0x4c, 0x69, 0x67, 0x74, 0x68, 0x50, 0x61, 0x79, 0x52, 0x65, 0x73,
	0x70, 0x22, 0x31, 0x0a, 0x13, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x56, 0x65, 0x72, 0x69, 0x66,
	0x79, 0x43, 0x6f, 0x64, 0x65, 0x52, 0x65, 0x71, 0x12, 0x1a, 0x0a, 0x08, 0x50, 0x68, 0x6f, 0x6e,
	0x65, 0x4e, 0x75, 0x6d, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x50, 0x68, 0x6f, 0x6e,
	0x65, 0x4e, 0x75, 0x6d, 0x22, 0x15, 0x0a, 0x13, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x56, 0x65,
	0x72, 0x69, 0x66, 0x79, 0x43, 0x6f, 0x64, 0x65, 0x52, 0x73, 0x70, 0x22, 0x69, 0x0a, 0x0f, 0x4c,
	0x6f, 0x67, 0x69, 0x6e, 0x42, 0x79, 0x50, 0x68, 0x6f, 0x6e, 0x65, 0x52, 0x65, 0x71, 0x12, 0x1a,
	0x0a, 0x08, 0x50, 0x68, 0x6f, 0x6e, 0x65, 0x4e, 0x75, 0x6d, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x08, 0x50, 0x68, 0x6f, 0x6e, 0x65, 0x4e, 0x75, 0x6d, 0x12, 0x1a, 0x0a, 0x08, 0x55, 0x73,
	0x65, 0x72, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x55, 0x73,
	0x65, 0x72, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x1e, 0x0a, 0x0a, 0x56, 0x65, 0x72, 0x69, 0x66, 0x79,
	0x43, 0x6f, 0x64, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x56, 0x65, 0x72, 0x69,
	0x66, 0x79, 0x43, 0x6f, 0x64, 0x65, 0x22, 0x59, 0x0a, 0x09, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x52,
	0x65, 0x73, 0x70, 0x12, 0x14, 0x0a, 0x05, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x05, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x12, 0x1a, 0x0a, 0x08, 0x50, 0x68, 0x6f,
	0x6e, 0x65, 0x4e, 0x75, 0x6d, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x50, 0x68, 0x6f,
	0x6e, 0x65, 0x4e, 0x75, 0x6d, 0x12, 0x1a, 0x0a, 0x08, 0x55, 0x73, 0x65, 0x72, 0x4e, 0x61, 0x6d,
	0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x55, 0x73, 0x65, 0x72, 0x4e, 0x61, 0x6d,
	0x65, 0x32, 0x3e, 0x0a, 0x09, 0x55, 0x73, 0x65, 0x72, 0x4c, 0x69, 0x67, 0x68, 0x74, 0x12, 0x31,
	0x0a, 0x08, 0x6c, 0x69, 0x67, 0x68, 0x74, 0x50, 0x61, 0x79, 0x12, 0x11, 0x2e, 0x75, 0x73, 0x65,
	0x72, 0x2e, 0x4c, 0x69, 0x67, 0x74, 0x68, 0x50, 0x61, 0x79, 0x52, 0x65, 0x71, 0x1a, 0x12, 0x2e,
	0x75, 0x73, 0x65, 0x72, 0x2e, 0x4c, 0x69, 0x67, 0x74, 0x68, 0x50, 0x61, 0x79, 0x52, 0x65, 0x73,
	0x70, 0x32, 0x88, 0x01, 0x0a, 0x04, 0x55, 0x73, 0x65, 0x72, 0x12, 0x48, 0x0a, 0x10, 0x43, 0x72,
	0x65, 0x61, 0x74, 0x65, 0x56, 0x65, 0x72, 0x69, 0x66, 0x79, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x19,
	0x2e, 0x75, 0x73, 0x65, 0x72, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x56, 0x65, 0x72, 0x69,
	0x66, 0x79, 0x43, 0x6f, 0x64, 0x65, 0x52, 0x65, 0x71, 0x1a, 0x19, 0x2e, 0x75, 0x73, 0x65, 0x72,
	0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x56, 0x65, 0x72, 0x69, 0x66, 0x79, 0x43, 0x6f, 0x64,
	0x65, 0x52, 0x73, 0x70, 0x12, 0x36, 0x0a, 0x0c, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x42, 0x79, 0x50,
	0x68, 0x6f, 0x6e, 0x65, 0x12, 0x15, 0x2e, 0x75, 0x73, 0x65, 0x72, 0x2e, 0x4c, 0x6f, 0x67, 0x69,
	0x6e, 0x42, 0x79, 0x50, 0x68, 0x6f, 0x6e, 0x65, 0x52, 0x65, 0x71, 0x1a, 0x0f, 0x2e, 0x75, 0x73,
	0x65, 0x72, 0x2e, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x42, 0x0d, 0x5a, 0x0b,
	0x61, 0x70, 0x69, 0x2f, 0x75, 0x73, 0x65, 0x72, 0x2f, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x33,
}

var (
	file_api_user_pb_user_proto_rawDescOnce sync.Once
	file_api_user_pb_user_proto_rawDescData = file_api_user_pb_user_proto_rawDesc
)

func file_api_user_pb_user_proto_rawDescGZIP() []byte {
	file_api_user_pb_user_proto_rawDescOnce.Do(func() {
		file_api_user_pb_user_proto_rawDescData = protoimpl.X.CompressGZIP(file_api_user_pb_user_proto_rawDescData)
	})
	return file_api_user_pb_user_proto_rawDescData
}

var file_api_user_pb_user_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_api_user_pb_user_proto_goTypes = []interface{}{
	(*LigthPayReq)(nil),         // 0: user.LigthPayReq
	(*LigthPayResp)(nil),        // 1: user.LigthPayResp
	(*CreateVerifyCodeReq)(nil), // 2: user.CreateVerifyCodeReq
	(*CreateVerifyCodeRsp)(nil), // 3: user.CreateVerifyCodeRsp
	(*LoginByPhoneReq)(nil),     // 4: user.LoginByPhoneReq
	(*TokenResp)(nil),           // 5: user.TokenResp
}
var file_api_user_pb_user_proto_depIdxs = []int32{
	0, // 0: user.UserLight.lightPay:input_type -> user.LigthPayReq
	2, // 1: user.User.CreateVerifyCode:input_type -> user.CreateVerifyCodeReq
	4, // 2: user.User.LoginByPhone:input_type -> user.LoginByPhoneReq
	1, // 3: user.UserLight.lightPay:output_type -> user.LigthPayResp
	3, // 4: user.User.CreateVerifyCode:output_type -> user.CreateVerifyCodeRsp
	5, // 5: user.User.LoginByPhone:output_type -> user.TokenResp
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_api_user_pb_user_proto_init() }
func file_api_user_pb_user_proto_init() {
	if File_api_user_pb_user_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_api_user_pb_user_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LigthPayReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_user_pb_user_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LigthPayResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_user_pb_user_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateVerifyCodeReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_user_pb_user_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateVerifyCodeRsp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_user_pb_user_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LoginByPhoneReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_user_pb_user_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TokenResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_api_user_pb_user_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_api_user_pb_user_proto_goTypes,
		DependencyIndexes: file_api_user_pb_user_proto_depIdxs,
		MessageInfos:      file_api_user_pb_user_proto_msgTypes,
	}.Build()
	File_api_user_pb_user_proto = out.File
	file_api_user_pb_user_proto_rawDesc = nil
	file_api_user_pb_user_proto_goTypes = nil
	file_api_user_pb_user_proto_depIdxs = nil
}
